load('s1.RData')
load('s2.RData')


bind <- rbind(s1,s2)
bind <- rbind(bind,s3)
bind <- rbind(bind,s4)
bind <- rbind(bind,s5)
bind <- rbind(bind,s6)
bind <- rbind(bind,s7)
bind <- rbind(bind,s8)
bind <- rbind(bind,s9)
bind <- rbind(bind,s10)
bind <- rbind(bind,s11)
bind <- rbind(bind,s12)
bind <- rbind(bind,s13)
bind <- rbind(bind,s14)
bind <- rbind(bind,s15)
bind <- rbind(bind,s16)
bind <- rbind(bind,s17)
bind <- rbind(bind,s18)
